name: Integración Continua - Trueque Verde

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Validar Código y Pruebas
    runs-on: ubuntu-latest
    

    env:
      PORT: 3000
      MONGO_URI: mongodb://localhost:27017/ci-test
      JWT_SECRET: secreto_super_seguro_para_github_actions

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Instalar dependencias
        run: npm ci

      - name: Ejecutar Linter (HU-15)
        run: npm run lint

      - name: Compilar TypeScript / Build (HU-15)
        run: npm run build

      - name: Ejecutar Tests (Unitarios y BDD) (HU-15)
        run: npm run test